### ISSUE TITLE
Inline editing not working if specifying single quotes.

### ISSUE THREAD

**Issue by sant123** [trentm/json#111]
Node: v.7.2.0
Json: v.9.0.4
OS: Windows
If I type this code:

``` bash
json -I -f config.json -e 'this.port=8080'
```

It won't work until I remove the single quotes: 

``` bash
json -I -f config.json -e this.port=8080
```

Is this the expected behaviour? The docs seems confusing. 

Thanks.

**Comment by trentm** [comment]
@sant123 Sorry for the delay in responding. No, that isn't expected behaviour. Here is an example of me doing it with and without quotes on Mac:

```
[23:10:41 trentm@danger0:~/tm/json (master)]
$ cat config.json
{
  "host": "example.com",
  "port": 8080
}
[23:10:45 trentm@danger0:~/tm/json (master)]
$ json -I -f config.json -e 'this.port=80'
json: updated "config.json" in-place
[23:10:52 trentm@danger0:~/tm/json (master)]
$ cat config.json
{
  "host": "example.com",
  "port": 80
}
[23:10:54 trentm@danger0:~/tm/json (master)]
$ json -I -f config.json -e this.port=8080
json: updated "config.json" in-place
[23:11:01 trentm@danger0:~/tm/json (master)]
$ cat config.json
{
  "host": "example.com",
  "port": 8080
}
```

My *guess* would be something to do with Windows. Can you try with double-quotes instead of single-quotes? I've been so long away from Windows that I don't recall what the single-quoting story is.

**Comment by sant123** [comment]
Do not worry @trentm, that happens 😄 as expected works with double-quotes. Thank you!

``` sh
json -I -f config.json -e "this.port=8080;this.name='MyApp'"
```
